server:
  port: 8867

spring:
  datasource:
    db-type: h2
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2/schema.sql
    data: classpath:db/h2/data.sql
    url: jdbc:h2:mem:iuv
    username: root
    password: root
  h2:
    console:
      enabled: true
  #      path: /h2-console

  redis:
    database: 0
    host: 139.196.190.46
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
