server:
  port: 8867

spring:
  application:
    name: iuv
  datasource:
    db-type: h2
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2/schema.sql
    data: classpath:db/h2/data.sql
    url: jdbc:h2:mem:iuv
    username: root
    password: root
  h2:
    console:
      enabled: true
  #      path: /h2-console

  redis:
    database: 0
    host: 139.196.190.46
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ===== 自定义swagger配置 ===== #
knife4j-swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: for my baby
  try-host: http://localhost:${server.port}

logging:
  level:
    me.jianghs.iuv: debug
    org.springframework.boot.autoconfigure.security: debug
#shiro:
#  sessionManager:
#    sessionIdCookieEnabled: true
#    sessionIdUrlRewritingEnabled: true
#  unauthorizedUrl: /unauthorizedurl
#  web:
#    enabled: true
#  successUrl: /index
#  loginUrl: /login
